### ISSUE TITLE
ParseError ?

### ISSUE THREAD

**Issue by bth006** [jim-olsen/StarlinkRemote#2]
Hi,

I'm pretty sure I've done something stupid... but I can't get "npm run build" to work without errors.  Are you able to help please?  Below   is the the problem.  Thanks
-------------------------------------

Ubuntu 22.04.1 LTS

$ node -v
v18.7.0
$ npm -v
8.15.0
tim@tim-VirtualBox:~/Documents/StarlinkRemote-master/src/svelte$ npm install

up to date, audited 288 packages in 4s

48 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
tim@tim-VirtualBox:~/Documents/StarlinkRemote-master/src/svelte$ npm run build

> svelte-app@1.0.0 build
> rollup -c

[rollup-plugin-svelte] Unknown "dev" option. Please use "compilerOptions" for any Svelte compiler configuration.
[rollup-plugin-svelte] Unknown "css" option. Please use "compilerOptions" for any Svelte compiler configuration.

src/main.js → public/bundle.js...
[!] (plugin svelte) ParseError: Attributes need to be unique
src/App.svelte
21:     <button class="tabButton" on:click={()=> {dashboard=true; outages=false;allComponents=false;}}>Dashboard</button>
22:     <button class="tabButton" on:click={()=> {dashboard=false; outages=true; allComponents=false;}}
23:     <button class="tabButton" on:click={()=> {dashboard=false; outages=false;allComponents=true;}}>All Components</button>
                ^
24: </div>
25: <StarlinkDataFetcher/>
ParseError: Attributes need to be unique
    at error (/home/tim/Documents/StarlinkRemote-master/src/svelte/node_modules/svelte/src/compiler/utils/error.ts:25:16)
    at Parser$1.error (/home/tim/Documents/StarlinkRemote-master/src/svelte/node_modules/svelte/src/compiler/parse/index.ts:101:3)
    at check_unique (/home/tim/Documents/StarlinkRemote-master/src/svelte/node_modules/svelte/src/compiler/parse/state/tag.ts:293:11)
    at read_attribute (/home/tim/Documents/StarlinkRemote-master/src/svelte/node_modules/svelte/src/compiler/parse/state/tag.ts:433:2)
    at tag (/home/tim/Documents/StarlinkRemote-master/src/svelte/node_modules/svelte/src/compiler/parse/state/tag.ts:166:22)
    at new Parser$1 (/home/tim/Documents/StarlinkRemote-master/src/svelte/node_modules/svelte/src/compiler/parse/index.ts:53:12)
    at parse (/home/tim/Documents/StarlinkRemote-master/src/svelte/node_modules/svelte/src/compiler/parse/index.ts:218:17)
    at compile (/home/tim/Documents/StarlinkRemote-master/src/svelte/node_modules/svelte/src/compiler/compile/index.ts:94:14)
    at Object.transform (/home/tim/Documents/StarlinkRemote-master/src/svelte/node_modules/rollup-plugin-svelte/index.js:111:21)
    at /home/tim/Documents/StarlinkRemote-master/src/svelte/node_modules/rollup/dist/shared/rollup.js:22826:37

**Comment by jim-olsen** [comment]
I've pushed a fix...  Was rushing to check something in before the weekend and apparently cut off some text in the process.  It should build fine now...
